### ISSUE TITLE
CancelTime response not parsed

### ISSUE THREAD

**Issue by Naved81** [studerw/td-ameritrade-client#10]
Hello,

I feel this is a simple issue, but I'm a newbie in programming this stuff. Anyhow, I've got a GTC stop loss order and the response is not being parsed properly it appears. 

Response and stack trace below, some response values changed to dummy values:

[ {
  "session" : "NORMAL",
  "duration" : "GOOD_TILL_CANCEL",
  "orderType" : "STOP",
  "cancelTime" : "2020-09-04",
  "complexOrderStrategyType" : "NONE",
  "quantity" : 50.0,
  "filledQuantity" : 0.0,
  "remainingQuantity" : 50.0,
  "requestedDestination" : "AUTO",
  "destinationLinkName" : "CDRG",
  "stopPrice" : 172.0,
  "orderLegCollection" : [ {
    "orderLegType" : "EQUITY",
    "legId" : 1,
    "instrument" : {
      "assetType" : "EQUITY",
      "cusip" : "90138F102",
      "symbol" : "TWLO"
    },
    "instruction" : "SELL",
    "positionEffect" : "CLOSING",
    "quantity" : 50.0
  } ],
  "orderStrategyType" : "SINGLE",
  "orderId" : 123456789,
  "cancelable" : true,
  "editable" : true,
  "status" : "WORKING",
  "enteredTime" : "2020-05-08T17:00:37+0000",
  "tag" : "WEB_GRID",
  "accountId" : ABCDEFGHID
} ]

Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.studerw.tda.model.account.CancelTime` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('2020-09-04')
 at [Source: (BufferedInputStream); line: 5, column: 18] (through reference chain: java.util.ArrayList[0]->com.studerw.tda.model.account.Order["cancelTime"])
	at com.studerw.tda.parse.DefaultMapper.fromJson(DefaultMapper.java:83)
	at com.studerw.tda.parse.TdaJsonParser.parseOrders(TdaJsonParser.java:130)
	at com.studerw.tda.client.HttpTdaClient.fetchOrders(HttpTdaClient.java:408)

Thanks.

**Comment by Naved81** [comment]
In the com.studerw.tda.model.account.Order class, I changed the JSON property "cancelTime" to a String instead of CancelTime and it seemed to do the trick.

I'm not sure if this is the right approach, though.

**Comment by studerw** [comment]
Let me take a look - But you're solution to create it to a String is absolutely fine. I'm going to change it to a LocalDate instead, I think, but if you want to submit the final PR in order to get the Git 'cred' let me know. :)

**Comment by Naved81** [comment]
Thanks, I don't think I need the git 'cred', still haven't learned how to use github properly either lol. 

I did want to ask what's the best approach for extending some of your framework? For example, I had to build the POJOs for the UserPreference API (https://api.tdameritrade.com/v1/userprincipals). I felt the cleanest way was to extend your HttpTdaClient class, but then had to make the TdaJsonParser, OkHttpClient and Logger variables public so I could access my extended client version. I guess the proper way would've been to make my changes to your HttpTdaClient and then check them in?

**Comment by studerw** [comment]
Thanks @Naved81, I just submitted a patch if you want to see how I did the official way. Essentially what I did was change that field from an object type to just a java LocalDate and add a special parser annotation to let Jackson Json know how to convert from String to LocalDate.
