### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by bosohn** [studerw/td-ameritrade-client#14]
Hi,

This is not really an issue. I just wanted to check with you whether you have any plans to add streaming API to your client.

Thanks

**Comment by studerw** [comment]
Yeah, I'm planning on doing it. I had already done (part of) it for their old XML API, so if the code is similar, it shouldn't be too hard. I'll take a look this holiday weekend.

**Comment by bosohn** [comment]
Hi,

I am wondering whether you have any updates on streaming API.

Thanks

**Comment by studerw** [comment]
Can you make a feature request issue with some more info at the Github <https://github.com/studerw/td-ameritrade-client/issues/new> repo itself, and include some info on how you'd want the API to work? For example, say you wanted to get a Quote every 10 seconds or so. Would you want to pass a callback function that is called on another thread or I could return a queue that you listen to. Just depends on what you want as I haven't had a use case like that myself.
