### ISSUE TITLE
No definition for "client id"

### ISSUE THREAD

**Issue by FreeGoldRush** [studerw/td-ameritrade-client#18]
The wiki refers to a "client id".  I can't see where this is defined or any description of where it comes from.  The wiki references the "Getting Started" page at TD Ameritrade, but the page linked says nothing about a "client id".  One clue is that the wiki says it is created "when you register your app".  After registering the app and successfully getting a refresh token I cannot find a "client id" anywhere.  They are providing a "consumer key".  Could this be it?   An account also has an account number and a login ID.  Are any of these a "client id"?

Thanks!

**Comment by FreeGoldRush** [comment]
The "client id" is the "Consumer Key" that TD gives you when you create your "app". 

Trial and error is a brilliant problem solver.

**Comment by FreeGoldRush** [comment]
Maybe a small edit on the documentation would be helpful, but everything works great.

**Comment by studerw** [comment]
I will update the wiki, thanks. Did you have a hard time obtaining your refresh token? I’ve got a process that might be easier, because the directions on the TDA dev site are really complicated.

**Comment by higgsja** [comment]
Would love to have you share it. Every time I have to do that it's like 
having my teeth drilled.

a

--


Thanks!
West Point 1976 H-3
	Join us! <https://hlh-tx.com> 	*Mission:* To measurably improve 
investor performance

"Data without validation is simply noise." -- J.A. Higgs
"Egoism: quoting yourself in public" -- J.A Higgs

**Comment by FreeGoldRush** [comment]
An easier process would be preferred.  The TD instructions work but it is indeed a bit like having your teeth drilled.
