### ISSUE TITLE
Theoretical Option Value returns the Mark

### ISSUE THREAD

**Issue by vphilipnyc** [studerw/td-ameritrade-client#24]
This isn't a bug in this codebase, but the TDA API seems to return the Mark, rather than the theoretical (Black-Scholes or otherwise) price.  It's always halfway between the Bid/Ask. 

It may make sense to either:
a) Comment out/Deprecate this property for now in the codebase with a comment about this bug
b) Use @JsonProperty("theoreticalOptionValue") on the `mark` property.

Probably makes sense to do a).

You can compare the value you get with TOS for proof.

**Comment by studerw** [comment]
Is this when getting quotes?

**Comment by vphilipnyc** [comment]
It happens when going through either the Option Chain or the Quotes API.   

Try it with one contract and look at the theoreticalOptionValue: https://developer.tdameritrade.com/option-chains/apis/get/marketdata/chains
You can use WYNN_073120P76, for example.  This is part of the JSON response.   The mark and the theoreticalOptionValue are both 2.42 in the JSON. In TOS, the mark is 2.420 and the theoretical price is currently 9.2.

  "putExpDateMap": {
    "2020-07-31:1": {
      "76.0": [
        {
          "putCall": "PUT",
          "symbol": "WYNN_073120P76",
          "description": "WYNN Jul 31 2020 76 Put (Weekly)",
          "exchangeName": "OPR",
          "bid": 1.88,
          "ask": 2.96,
          "last": 2.02,
          "mark": 2.42,
          "bidSize": 20,
          "askSize": 16,
          "bidAskSize": "20X16",
          "lastSize": 0,
          "highPrice": 0,
          "lowPrice": 0,
          "openPrice": 0,
          "closePrice": 1.95,
          "totalVolume": 0,
          "tradeDate": null,
          "tradeTimeInLong": 1596052470363,
          "quoteTimeInLong": 1596052798626,
          "netChange": -1.54,
          "volatility": 159.061,
          "delta": -0.359,
          "gamma": 0.04,
          "theta": -0.866,
          "vega": 0.022,
          "rho": -0.002,
          "openInterest": 189,
          "timeValue": 1.31,
          "theoreticalOptionValue": 2.42,
          "theoreticalVolatility": 29,
          "optionDeliverablesList": null,
          "strikePrice": 76,
          "expirationDate": 1596225600000,
          "daysToExpiration": 1,
          "expirationType": "S",
          "lastTradingDay": 1596240000000,
          "multiplier": 100,
          "settlementType": " ",
          "deliverableNote": "",
          "isIndexOption": null,
          "percentChange": -78.66,
          "markChange": 0.47,
          "markPercentChange": 23.84,
          "inTheMoney": true,
          "nonStandard": false,
          "mini": false
        }
      ]
    },

Here is the response from the quotes API:

{
  "WYNN_073120P76": {
    "assetType": "OPTION",
    "assetMainType": "OPTION",
    "cusip": "0WYNN.SV00076000",
    "symbol": "WYNN_073120P76",
    "description": "WYNN Jul 31 2020 76 Put (Weekly)",
    "bidPrice": 1.88,
    "bidSize": 20,
    "askPrice": 2.96,
    "askSize": 16,
    "lastPrice": 2.02,
    "lastSize": 25,
    "openPrice": 0,
    "highPrice": 0,
    "lowPrice": 0,
    "closePrice": 1.9541,
    "netChange": -1.5371,
    "totalVolume": 0,
    "quoteTimeInLong": 1596052798626,
    "tradeTimeInLong": 1596052470363,
    "mark": 2.42,
    "openInterest": 189,
    "volatility": 159.0611,
    "moneyIntrinsicValue": 0.71,
    "multiplier": 100,
    "digits": 2,
    "strikePrice": 76,
    "contractType": "P",
    "underlying": "WYNN",
    "expirationDay": 31,
    "expirationMonth": 7,
    "expirationYear": 2020,
    "daysToExpiration": 1,
    "timeValue": 1.31,
    "deliverables": "",
    "delta": -0.359,
    "gamma": 0.0403,
    "theta": -0.866,
    "vega": 0.0218,
    "rho": -0.0016,
    "securityStatus": "Normal",
    "theoreticalOptionValue": 2.42,
    "underlyingPrice": 75.29,
    "uvExpirationType": "S",
    "exchange": "o",
    "exchangeName": "OPR",
    "lastTradingDay": 1596240000000,
    "settlementType": " ",
    "netPercentChangeInDouble": -78.6603,
    "markChangeInDouble": 0.4659,
    "markPercentChangeInDouble": 23.8422,
    "delayed": false
  }
}

**Comment by studerw** [comment]
I sent an email with the issue to api@tdameritrade.com. Let's see if they reply. If not, I'd agree with your first option to just comment out the property. Better to not even return it to the user than return a bad value that could cost someone money.

**Comment by studerw** [comment]
@vphilipnyc FYI:

I got a response from the the TDA dev team:

Hello,

The theoretical option values between our API and thinkorswim are 100% separate.  We are working internally to try to match the values provided on the API to match that of thinkorswim, but we do not have an ETA for when this will be finished.

Kind regards,

Michael Ying
Product Manager, Trader
TD Ameritrade
600 W Chicago Ave, Chicago, IL 60654
T 866-839-1100
