### ISSUE TITLE
getUserPrincipals() is missing a "fields" paramater

### ISSUE THREAD

**Issue by outstaller** [studerw/td-ameritrade-client#32]
Thanks for the java implementation.

Trying to get streaming quotes going with this and the main hurdle right now is that the getUserPrincipals() call is missing a fields argument 
Per the guide at https://developer.tdameritrade.com/content/streaming-data#_Toc504640599 I'd need to provide streamerSubscriptionKeys,streamerConnectionInfo in the fields query param in order to get the keys and info for streaming.

Sidenote, I'd recommend making the following fields protected to allow for subclassing and extending of HttpTdaClient:

  final TdaJsonParser tdaJsonParser = new TdaJsonParser();
  final OkHttpClient httpClient;
  private HttpUrl httpUrl;

Thanks again for this.

**Comment by studerw** [comment]
@outstaller 

I added the Fields parameters to the Userprincipals and checked into master. I'll make a new release later this week.

I just looked your recommendations for making certain fields protected.

TdaJsonParser doesn't actually implement any interface, so you'd have to modify the class anyway. 

HttpClient would definitely make sense and maybe HttpUrl (but maybe that would just be part of HttpClient). Do you have any code or other examples of what you'd like to see?
