### ISSUE TITLE
fix javadoc

### ISSUE THREAD

**Issue by abramcat** [studerw/td-ameritrade-client#51]
In file PriceHistReq, javadoc at top:
PriceHistReq request = PriceHistReqBuilder.priceHistReq()

believe it should be:
PriceHistReq request = PriceHistReq.Builder.priceHistReq()

**Comment by studerw** [comment]
@thanks @abramcat . Fixed and commited!

**Comment by abramcat** [comment]
thank you for the library!

sorry my git-foo isn't up to making the commit pull request myself... I'm an old perforce/SVN soul. Soon.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
