### ISSUE TITLE
Generating a new access token with every API call

### ISSUE THREAD

**Issue by gporter0205** [studerw/td-ameritrade-client#53]
@studerw I'm not sure if this is the way it's supposed to work or if I'm doing something wrong in my implementation of the API, but every call I make generates a new access token.  I actually got called out by the TDA API team for generating "excessive" access tokens on a daily basis.  I'm working my way through all the documentation and debugging the code to figure out if I'm doing something wrong, but thought I would check with the source while doing that.  Thanks Greg.
![Screenshot 2022-01-03 113016](https://user-images.githubusercontent.com/85386574/147961053-b8e62bca-8a9d-49db-80e9-907020080ad2.png)

**Comment by gporter0205** [comment]
Nvm, I found the problem in my implementation of the API.  I was recreating the HttpTdaClient object every time I used it instead of reusing the one that had already been authenticated.

**Comment by studerw** [comment]
@gporter0205 Thanks for the tip. I'll add a warning in the README and docs to avoid constantly recreating that which could happen easily in a Spring or similar DI environment if you're not careful to create it as a Singleton.
