### ISSUE TITLE
Vulnerabilities from dependencies

### ISSUE THREAD

**Issue by jschlade** [studerw/td-ameritrade-client#60]
Hi,

Are you going to do a 2.4.2 release with fixes for these vulnerabilities?

https://mvnrepository.com/artifact/com.studerw.tda/td-ameritrade-client/2.4.1

Thanks

**Comment by studerw** [comment]
Hi @jschlade - I pushed a new release 2.4.2 to Maven central. Let me know if you still get security issues with your scanner. 

I still see some "vulnerabilities" from various scanners e.g. Sonatype and IntelliJ, but they seem minor; this release resolves the bigger issues being reported by Github related to jackson.
