### ISSUE TITLE
Schwab API

### ISSUE THREAD

**Issue by gporter0205** [studerw/td-ameritrade-client#65]
Hi @studerw.  Have you heard anything about the TDA API being migrated to Schwab?  My accounts migrate over the weekend and I haven't seen anything other than superficial about it migrating "some day".  Just curious if you had heard anything?

Thanks
Greg

**Comment by studerw** [comment]
Hi @gporter0205 

Yes over the past few months I got numerous notices telling me that my two TDA account (one personal and one from my Health Savings account) would be moving to Schwab.

On October 1st, the HSA account was moved over and when I logged into Schwab after Oct 1st, I would see it as an additional Schwab account (I already had a Schwab trading account from years ago).

Then finally last week or so, my personal TDA account was also moved over to Schwab. So now I see 3 accounts in my Schwab profile. I verified this one for the first time today.

As a test, I tried to log into my TDA acccount just now. I did the typical user & password screen and then the SMS verification, but instead of forwarding me to TDA page, it just shows a button that says "Log Into Schwab."

So it would appear my TDA accounts are are completely migrated, and my TDA access is gone. 

That's that :(

**Comment by karthik134** [comment]
@studerw - Thank you for creating this and maintaining it. With the migration to Schwab, does this repo code still work. Based on their description in Ameritrade Developer portal, it looks like they will use the Ameritrade API behind the scenes, but I might be wrong.

**Comment by karthik134** [comment]
@studerw - checking back on this. does this work with Schwab APIs. Or do you plan to update this repo or open a new one to support the Schwab APIs.

**Comment by mntripathi** [comment]
@studerw Thanks for maintaining this project for TDA, is there any plan to migrate this API to new Schwab API?

**Comment by studerw** [comment]
I’ve not been able to get access to Schwab API yet though once I do (if they ever actually provide it) then I may try and port it over.

**Comment by mntripathi** [comment]
My account is still with TDA and moving on 10th May. I tried creating a new app in Schwab Developer yesterday, and I was able to create. I can see all APIs, Swagger page etc. (I never received any email from Schwab to create Application, while I created Developer account in August 2023) Steps I followed
1. Signin https://developer.schwab.com/
2. Create App https://developer.schwab.com/dashboard/apps
3. Select both API Products (currently showing only 2 APIs)
4. they need https endpoint for URL redirect (i used https://127.0.01)
5. Just after creating app, approval status will go in "Approved - Pending" check in Dashboard link
6. It takes 1 week to get approved for "Ready to use" but after above 4 steps we can start implementing the APIs.

![ScreenShot](https://github.com/studerw/td-ameritrade-client/assets/3408377/12fe8275-ed63-43ae-ae41-09e652349b89)

**Comment by gporter0205** [comment]
I got an email on Friday saying I could start development using the Schwab Trader API so I went to the developer portal and requested access. Hopefully, I'll be able to poke around with the new Schwab API next week. I've upgraded my app to use spring boot API calls. I'd be willing to help port this app. Any interest in upgrading it and using spring boot?

**Comment by mntripathi** [comment]
@studerw, all
we have only 2 weeks remaining for final move. let me know if anyone is building schwab api? I would like to collaborate

**Comment by gporter0205** [comment]
@mntripathi I've been working on it as I've had free time, but am still working on the authentication part of it.  I was trying to use the oauth2 features built in to spring boot, but after wrestling with it for a while, finally gave up because the TD/Schwab implementation of oauth2 isn't exactly "standard".  It also doesn't help that every time I change something about my app on developer.schwab.com, it takes several days to week(s) for it to be approved and be able to use the API again.  The most recent change I made to the callback URLs is going on over a week now.  I finally sent them an email about it yesterday.  It's also been maddeningly difficult to do development because you can't use http or localhost in the callback URL so I've had to find workarounds for that and every time I need to change the callback to try something else, I have to wait days/week(s) for it to be approved again.  Rinse and repeat.  So far it's been a very frustrating experience.

**Comment by fear025** [comment]
There's been some great discussion about the authentication and other issues over on the "Charles Schwab API Club" on Discord. Here's the invite: https://discord.gg/9D4Bnm4B74

**Comment by mntripathi** [comment]
@gporter0205 you can use "https://127.0.0.1" it works. (at least I am able to register my app with this callback URL and app is approved),

**Comment by gporter0205** [comment]
Thanks @fear025. I had a breakthrough on the oauth today after reading through the Discord comments. Found exactly what I was doing wrong! 

Thanks also @mntripathi. I'll give that a try too.

**Comment by gporter0205** [comment]
I create a new github project for the Schwab API.  I made it a Spring Boot project for ease of a lot of things.  So far I've only implemented the quote API's, but I'll be working on more as I have time.  https://github.com/gporter0205/schwab-api-client

**Comment by gporter0205** [comment]
I've implemented the happy path for all the market data API end points.  I also created a readme and some initial how-to implement documentation.  I won't post updates here anymore, but you should be able to see progress in https://github.com/gporter0205/schwab-api-client

**Comment by sivadosapati** [comment]
@gporter0205 -> Thank you for creating this API. I've been trying to play with it but I'm stuck at getting refresh tokens. Any help will be greatly appreciated.

**Comment by gporter0205** [comment]
@sivadosapati can you open an issue over on https://github.com/gporter0205/schwab-api-client?  That way working our communication while working through your issue will be documented and can help someone else facing them same issue.
