### ISSUE TITLE
Application Not working

### ISSUE THREAD

**Issue by ajaythukral** [studerw/td-ameritrade-client#68]
Hi, 
With The transition of TDameritrade to Schwab , My application is not working as it was not able to generate bearer token from Refresh token passed and also end points has also changed. Could you suggest what changes needs to be done to make it work.
Thanks
Ajay

**Comment by studerw** [comment]
Hi Ajay- as best as we can tell, once you’ve switched over to Schwab, this TDA library will no longer work. 

Apparently Schwab has finally begun giving developers access to their new API (which, again, is not compatible with this Lib), and a few devs were working on it and have began a project to access it via Java, similar to this project.

 Please see one of the previous issue tickets for more info.
